name: CI/CD Pipeline

on:
    push:
        branches:
            - main # Change this to your default branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "21" # Change to your version

            - name: Install dependencies
              run: npm install # Modify if using another package manager

            - name: Run tests
              run: npm test  -- --passWithNoTests # Added flag here

    deploy:
        runs-on: ubuntu-latest
        needs: build # Ensure deployment only happens after a successful build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy files to server
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$SSH_PRIVATE_KEY" > private_key
                  chmod 600 private_key
                  rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no -p 4444" ./ debabrata@192.168.68.108:/Projects/dkt-type-backend
                  rm private_key
